version: '3.8'

services:
  # Server service
  server:
    build:
      context: ../server
      dockerfile: ../infra/docker/server/Dockerfile.dev
    container_name: neurallog-server
    ports:
      - "3030:3030"
    volumes:
      - ../server:/app
      - server_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3030
      - REDIS_URL=redis://redis:6379
      - AUTH_URL=http://auth:3000
      - LOG_LEVEL=debug
    depends_on:
      - redis
      - auth
    command: npm run dev

  # Redis service
  redis:
    image: redis:7-alpine
    container_name: neurallog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: neurallog-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

  # Auth service
  auth:
    build:
      context: ../auth
      dockerfile: ../infra/docker/auth/Dockerfile.dev
    container_name: neurallog-auth
    ports:
      - "3040:3000"
    volumes:
      - ../auth:/app
      - auth_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - OPENFGA_HOST=openfga
      - OPENFGA_PORT=8080
      - OPENFGA_ADAPTER_TYPE=local
      - LOG_LEVEL=debug
    depends_on:
      - openfga
      - postgres
    command: npm run dev

  # OpenFGA service
  openfga:
    image: openfga/openfga:latest
    container_name: neurallog-openfga
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:postgres@postgres:5432/openfga
      - OPENFGA_AUTHN_METHOD=none
      - OPENFGA_LOG_LEVEL=info
      - OPENFGA_PLAYGROUND_ENABLED=true
    depends_on:
      - postgres
    restart: unless-stopped

  # PostgreSQL service
  postgres:
    image: postgres:14-alpine
    container_name: neurallog-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=openfga
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  server_node_modules:
  auth_node_modules:
  redis-data:
  postgres-data:
    driver: local
