version: '3.8'

services:
  # PostgreSQL for OpenFGA
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: openfga
      POSTGRES_PASSWORD: openfga
      POSTGRES_DB: openfga
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - neurallog-network
    restart: unless-stopped

  # OpenFGA migrations
  openfga-migrate:
    image: openfga/openfga:latest
    container_name: openfga-migrate
    command: migrate
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgresql://openfga:openfga@postgres:5432/openfga
    networks:
      - neurallog-network
    depends_on:
      - postgres

  # OpenFGA server
  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    command: run
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgresql://openfga:openfga@postgres:5432/openfga
      OPENFGA_LOG_FORMAT: json
      OPENFGA_AUTHN_METHOD: none
      OPENFGA_PLAYGROUND_ENABLED: "true"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - neurallog-network
    depends_on:
      - openfga-migrate
    restart: unless-stopped

  # Auth service
  auth:
    image: node:22-alpine
    container_name: auth-service
    working_dir: /app
    volumes:
      - ../auth:/app
    environment:
      NODE_ENV: development
      PORT: 3040
      OPENFGA_API_URL: http://openfga:8080
      DEFAULT_TENANT_ID: default
    ports:
      - "3040:3040"
    command: sh -c "npm config set registry http://verdaccio:4873 ; npm install ; npm run build ; npm start"
    networks:
      - neurallog-network
    depends_on:
      - openfga
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  neurallog-network:
    external: true
