kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30030
    hostPort: 30030
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 30031
    hostPort: 30031
    protocol: TCP
