apiVersion: v1
kind: Service
metadata:
  name: neurallog-server
  labels:
    app: neurallog-server
spec:
  selector:
    app: neurallog-server
  ports:
  - port: 3030
    targetPort: http
    name: http
  type: ClusterIP
