apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- server/deployment.yaml
- server/service.yaml
- redis/statefulset.yaml
- redis/service.yaml
- redis/configmap.yaml

namespace: neurallog
