apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
  labels:
    app: openfga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfga
  template:
    metadata:
      labels:
        app: openfga
    spec:
      containers:
      - name: openfga
        image: openfga/openfga:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: grpc
        - containerPort: 3000
          name: metrics
        env:
        - name: OPENFGA_DATASTORE_ENGINE
          value: "postgres"
        - name: OPENFGA_DATASTORE_URI
          valueFrom:
            secretKeyRef:
              name: openfga-postgres-credentials
              key: connection-string
        - name: OPENFGA_LOG_FORMAT
          value: "json"
        - name: OPENFGA_LOG_LEVEL
          value: "info"
        - name: OPENFGA_AUTHN_METHOD
          value: "none"  # No authentication for internal service
        - name: OPENFGA_PLAYGROUND_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
