apiVersion: v1
kind: Service
metadata:
  name: openfga
  labels:
    app: openfga
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: grpc
  - port: 3000
    targetPort: 3000
    name: metrics
  selector:
    app: openfga
