name: Operator Deploy

on:
  workflow_run:
    workflows: ["Operator Docker Build and Push"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment: ${{ github.event.inputs.environment || 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.0.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Set image tag
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment || 'staging' }}
          if [ "$ENVIRONMENT" == "production" ]; then
            TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
          else
            TAG=sha-$(git rev-parse --short HEAD)
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Update kustomization.yaml
        working-directory: ./operator/config/manager
        run: |
          kustomize edit set image controller=ghcr.io/neurallog/operator:${{ env.IMAGE_TAG }}

      - name: Deploy operator
        working-directory: ./operator/config
        run: |
          kubectl apply -k .

      - name: Verify deployment
        run: |
          kubectl -n neurallog-system rollout status deployment/neurallog-operator-controller-manager --timeout=300s
